# EpoxymDNS - Async Service Discovery Example Makefile

APP_NAME := AsyncServiceDiscovery
ARDUINO_LIBS := EpoxymDNS
EPOXY_DUINO := ../../../..
LDFLAGS := -lpthread -lavahi-client -lavahi-common
include $(EPOXY_DUINO)/EpoxyDuino.mk
