# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

EXTRA_CXXFLAGS=-g3 -O0

APP_NAME := SimulatedTimeTest
ARDUINO_LIBS := AUnit

include ../next.mk
