# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

#EXTRA_CXXFLAGS=-O3 -DEPOXY_TEST_DEBUG
EXTRA_CXXFLAGS=-g3 -O0 -DEPOXY_TEST_DEBUG

APP_NAME := ScriptInjection
ARDUINO_LIBS := AUnit

include ../next.mk
