# EpoxymDNS - Minimal Makefile Example

APP_NAME := ServiceDiscovery
ARDUINO_LIBS := EpoxymDNS
EPOXY_DUINO := ../../../..
LDFLAGS := -lpthread -lavahi-client -lavahi-common
include $(EPOXY_DUINO)/EpoxyDuino.mk
