name: AUnit Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libc++-dev

    - name: Setup Arduino libraries
      run: |
        cd ..
        git clone https://github.com/hsaturn/AUnit
        git clone https://github.com/bxparks/AceCommon
        git clone https://github.com/bxparks/AceCRC
        git clone https://github.com/bxparks/AceUtils
        git clone https://github.com/bxparks/AceRoutine

    - name: Verify examples
      run: |
        make -C examples
        make -C libraries examples

    - name: Verify tests
      run: |
        # tests/IPAddressTest requires EPOXY_CORE_ESP8266, which requires clean
        make -C tests clean
        make -C tests tests
        make -C tests runtests
        # clean after tests/IPAddressTest to revert to EPOXY_CORE_AVR
        make -C libraries clean
        make -C libraries tests
        make -C libraries runtests
